services:
    fm.script_service:
        class: MSDev\DoctrineFileMakerDriver\Utility\ScriptAccess
        arguments:
            - '@doctrine.dbal.default_connection'
        public: true
    MSDev\DoctrineFileMakerDriver\Utility\ScriptAccess: '@fm.script_service'

    fm.container_service:
        class: MSDev\DoctrineFileMakerDriver\Utility\ContainerAccess
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@fm.script_service'
        public: true
    MSDev\DoctrineFileMakerDriver\Utility\ContainerAccess: '@fm.container_service'

    fm.valuelist_service:
        class: MSDev\DoctrineFileMakerDriverBundle\Service\ValuelistManager
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@session'
        public: true
    MSDev\DoctrineFileMakerDriverBundle\Service\ValuelistManager: '@fm.valuelist_service'

    fm.twig.render_select:
        class: MSDev\DoctrineFileMakerDriverBundle\Twig\SelectExtension
        arguments:
            - '@fm.valuelist_service'
        tags:
            - { name: twig.extension }
        public: true
    MSDev\DoctrineFileMakerDriverBundle\Twig\SelectExtension: '@fm.twig.render_select'