<?php

namespace MSDev\DoctrineFileMakerDriverBundle\Repository;

/**
 * WebContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebContentRepository extends \Doctrine\ORM\EntityRepository
{
}
